<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\posts;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class postsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $posts = [
            [
                //id 1
                'id_user' => 1,
                'id_category' => 1,
                'id_community' => 1,
                'title' => "Farmers on Strike: A Call for Change",
                'description' => "In a significant turn of events, tractor drivers across the region have initiated a strike, bringing to light longstanding grievances within the agricultural sector. ",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                //id 2
                'id_user' => 1,
                'id_category' => 1,
                'id_community' => 1,
                'title' => "Innovation Meets Agriculture",
                'description' => "In a bold step towards sustainable agriculture, a new farm has been established, setting a benchmark for future farming practices.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                //id 3
                'id_user' => 1,
                'id_category' => 1,
                'id_community' => 1,
                'title' => "Rent the Latest in Farming Efficiency",
                'description' => "Unlock the potential of your farm with our cutting-edge agricultural tools available for rent! ",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                //id 4
                'id_user' => 1,
                'id_category' => 1,
                'id_community' => 1,
                'title' => "Premier Tool Rental Services",
                'description' => "Step into the future of farming with our premier tool rental services! Our extensive catalog features everything from high-efficiency soil tillers to advanced irrigation systems, all available at competitive rental rates.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                //id 5
                'id_user' => 2,
                'id_category' => 2,
                'id_community' => 2,
                'title' => "Discover Our New Collection of Organic Vegetables",
                'description' => "Explore our latest harvest of organic vegetables, grown with care and sustainability in mind. From crisp lettuce to vibrant tomatoes, our farm-fresh produce is sure to delight your taste buds!",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 6
                'id_user' => 2,
                'id_category' => 5,
                'id_community' => 2,
                'title' => "Farm-to-Table Dining Experience",
                'description' => "Join us for a farm-to-table dining experience like no other! Indulge in a culinary journey featuring the freshest ingredients sourced directly from our farm to your plate.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 7
                'id_user' => 2,
                'id_category' => 3,
                'id_community' => 3,
                'title' => "Tools for Home Improvement",
                'description' => "Upgrade your home with our wide selection of tools for every home improvement project. From power drills to paintbrushes, we have everything you need to tackle your next DIY endeavor.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 8
                'id_user' => 2,
                'id_category' => 3,
                'id_community' => 3,
                'title' => "Transform Your Living Space",
                'description' => "Revitalize your living space with our stylish and functional home decor solutions. From cozy throws to elegant wall art, our curated collection will help you create a home that reflects your unique style.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 9
                'id_user' => 2,
                'id_category' => 4,
                'id_community' => 4,
                'title' => "Stay Active with Our Fitness Equipment",
                'description' => "Elevate your fitness routine with our premium selection of exercise equipment. From cardio machines to strength training gear, we have everything you need to stay active and healthy.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 10
                'id_user' => 2,
                'id_category' => 4,
                'id_community' => 4,
                'title' => "Achieve Your Fitness Goals",
                'description' => "Reach new heights in your fitness journey with our expertly crafted workout plans and personalized training sessions. Whether you're a beginner or a seasoned athlete, we're here to help you achieve your fitness goals.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 11
                'id_user' => 2,
                'id_category' => 2,
                'id_community' => 5,
                'title' => "Explore the World of Technology",
                'description' => "Immerse yourself in the latest technological innovations with our wide range of gadgets and electronics. From smartphones to smart home devices, we have everything you need to stay connected and informed.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 12
                'id_user' => 2,
                'id_category' => 2,
                'id_community' => 5,
                'title' => "Upgrade Your Tech Game",
                'description' => "Stay ahead of the curve with our cutting-edge tech products and accessories. Whether you're a casual user or a tech enthusiast, our curated collection has something for everyone.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 13
                'id_user' => 2,
                'id_category' => 3,
                'id_community' => 6,
                'title' => "Unleash Your Creative Potential",
                'description' => "Fuel your creativity with our wide selection of art supplies and crafting materials. From paints to brushes, we have everything you need to bring your artistic vision to life.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 14
                'id_user' => 2,
                'id_category' => 6,
                'id_community' => 6,
                'title' => "Express Yourself Through Art",
                'description' => "Discover the joy of self-expression through art with our diverse range of creative workshops and classes. Whether you're a beginner or an experienced artist, our expert instructors will guide you every step of the way.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                //id 15
                'id_user' => 2,
                'id_category' => 1,
                'id_community' => 2,
                'title' => "New Innovations in Farming Technology",
                'description' => "Stay up to date with the latest advancements in farming technology with our informative seminars and hands-on workshops. Learn how to optimize your farm operations for maximum efficiency and sustainability.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 1,
                'id_community' => 1,
                'title' => "Farmers on Strike: A Call for Change",
                'description' => "In a significant turn of events, tractor drivers across the region have initiated a strike, bringing to light longstanding grievances within the agricultural sector.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 2,
                'id_community' => 2,
                'title' => "Discover Our New Collection of Organic Vegetables",
                'description' => "Explore our latest harvest of organic vegetables, grown with care and sustainability in mind. From crisp lettuce to vibrant tomatoes, our farm-fresh produce is sure to delight your taste buds!",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 3,
                'id_community' => 3,
                'title' => "Tools for Home Improvement",
                'description' => "Upgrade your home with our wide selection of tools for every home improvement project. From power drills to paintbrushes, we have everything you need to tackle your next DIY endeavor.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 4,
                'id_community' => 4,
                'title' => "Stay Active with Our Fitness Equipment",
                'description' => "Elevate your fitness routine with our premium selection of exercise equipment. From cardio machines to strength training gear, we have everything you need to stay active and healthy.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 5,
                'id_community' => 2,
                'title' => "Farm-to-Table Dining Experience",
                'description' => "Join us for a farm-to-table dining experience like no other! Indulge in a culinary journey featuring the freshest ingredients sourced directly from our farm to your plate.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 6,
                'id_community' => 6,
                'title' => "Express Yourself Through Art",
                'description' => "Discover the joy of self-expression through art with our diverse range of creative workshops and classes. Whether you're a beginner or an experienced artist, our expert instructors will guide you every step of the way.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 1,
                'id_community' => 3,
                'title' => "Transform Your Living Space",
                'description' => "Revitalize your living space with our stylish and functional home decor solutions. From cozy throws to elegant wall art, our curated collection will help you create a home that reflects your unique style.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 2,
                'id_community' => 5,
                'title' => "Upgrade Your Tech Game",
                'description' => "Stay ahead of the curve with our cutting-edge tech products and accessories. Whether you're a casual user or a tech enthusiast, our curated collection has something for everyone.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 3,
                'id_community' => 4,
                'title' => "Achieve Your Fitness Goals",
                'description' => "Reach new heights in your fitness journey with our expertly crafted workout plans and personalized training sessions. Whether you're a beginner or a seasoned athlete, we're here to help you achieve your fitness goals.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 4,
                'id_community' => 6,
                'title' => "Unleash Your Creative Potential",
                'description' => "Fuel your creativity with our wide selection of art supplies and crafting materials. From paints to brushes, we have everything you need to bring your artistic vision to life.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 1,
                'id_community' => 2,
                'title' => "New Innovations in Farming Technology",
                'description' => "Stay up to date with the latest advancements in farming technology with our informative seminars and hands-on workshops. Learn how to optimize your farm operations for maximum efficiency and sustainability.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 2,
                'id_community' => 5,
                'title' => "Explore the World of Technology",
                'description' => "Immerse yourself in the latest technological innovations with our wide range of gadgets and electronics. From smartphones to smart home devices, we have everything you need to stay connected and informed.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 3,
                'id_community' => 6,
                'title' => "Premier Tool Rental Services",
                'description' => "Step into the future of farming with our premier tool rental services! Our extensive catalog features everything from high-efficiency soil tillers to advanced irrigation systems, all available at competitive rental rates.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 4,
                'id_community' => 4,
                'title' => "Transform Your Living Space",
                'description' => "Revitalize your living space with our stylish and functional home decor solutions. From cozy throws to elegant wall art, our curated collection will help you create a home that reflects your unique style.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 5,
                'id_community' => 2,
                'title' => "Innovation Meets Agriculture",
                'description' => "In a bold step towards sustainable agriculture, a new farm has been established, setting a benchmark for future farming practices.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 6,
                'id_community' => 6,
                'title' => "Discover the Joy of Gardening",
                'description' => "Embark on a journey of discovery as you explore the world of gardening with us. From cultivating vibrant flowers to nurturing flavorful herbs, our expert tips and advice will help you create a garden oasis in your own backyard.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 1,
                'id_community' => 1,
                'title' => "Rent the Latest in Farming Efficiency",
                'description' => "Unlock the potential of your farm with our cutting-edge agricultural tools available for rent! ",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 2,
                'id_community' => 5,
                'title' => "Upgrade Your Tech Game",
                'description' => "Stay ahead of the curve with our cutting-edge tech products and accessories. Whether you're a casual user or a tech enthusiast, our curated collection has something for everyone.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'advertisement',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 3,
                'id_community' => 3,
                'title' => "Tools for Home Improvement",
                'description' => "Upgrade your home with our wide selection of tools for every home improvement project. From power drills to paintbrushes, we have everything you need to tackle your next DIY endeavor.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 2,
                'id_category' => 4,
                'id_community' => 4,
                'title' => "Stay Active with Our Fitness Equipment",
                'description' => "Elevate your fitness routine with our premium selection of exercise equipment. From cardio machines to strength training gear, we have everything you need to stay active and healthy.",
                'isActive' => 1,
                'private' => 0,
                'type' => 'post',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            // Añade más registros según sea necesario
        ];

        DB::table('posts')->insert($posts);
    }
}
